### ISSUE TITLE
Tokens should contain version

### ISSUE THREAD

**Issue by memlucky71** [Carrene/restfulpy#124]
We have two options for token versioning. 
 - Insert version number to token payload
 - Hash token version to token secret

**Comment by mahdi13** [comment]
@memlucky71 I didn't understand. Do you mean authorization token (JWT)? Why we need versioning?

**Comment by pylover** [comment]
Agents are storing tokens for a while, so what happens if token payload schema is changed? for example, adding a new field into payload will not be applied until user logout and or when the token is expired.

The version in token header helps clients to force regenerate token if the version does not match the `/apiv1/version`

**Comment by pylover** [comment]
@memlucky71 thoughts?
