### ISSUE TITLE
Travis does not work on release/v2 branch and its PRs

### ISSUE THREAD

**Issue by ArashFatahzade** [Carrene/restfulpy#309]
The Travis does not trigger on `release/v2` branch and its PRs. This branch should be added to `.travis.yml`.

https://github.com/Carrene/restfulpy/blob/1c7735512f7d3afda815517379b42ec45ab3085d/.travis.yml#L5-L9

**Comment by Malex** [comment]
The reason is actually pretty simple: v([1-9]\d*!)  matches only a v1, v10, v95 and so on, due to greediness.
v([1-9]*!) seems to work fine
(here some tests done in javascript:
`v = /^(release\/)?v([1-9]*!)?(0|[1-9]\d*)(\.(0|[1-9]\d*))*((a|b|rc)(0|[1-9]\d*))?(\.post(0|[1-9]\d*))?(\.dev(0|[1-9]\d*))?$/
/^(release\/)?v([1-9]*!)?(0|[1-9]\d*)(\.(0|[1-9]\d*))*((a|b|rc)(0|[1-9]\d*))?(\.post(0|[1-9]\d*))?(\.dev(0|[1-9]\d*))?$/
"release/v2".match(v)
(13) ["release/v2", "release/", undefined, "2", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, index: 0, input: "release/v2", groups: undefined]
"release/v24".match(v)
(13) ["release/v24", "release/", undefined, "24", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, index: 0, input: "release/v24", groups: undefined]
"release/v24.33".match(v)
(13) ["release/v24.33", "release/", undefined, "24", ".33", "33", undefined, undefined, undefined, undefined, undefined, undefined, undefined, index: 0, input: "release/v24.33", groups: undefined]
"release/v24.31.3.dev5".match(v)
(13) ["release/v24.31.3.dev5", "release/", undefined, "24", ".3", "3", undefined, undefined, undefined, undefined, undefined, ".dev5", "5", index: 0, input: "release/v24.31.3.dev5", groups: undefined]
"release/v1!24.31.3.dev5".match(v)
(13) ["release/v1!24.31.3.dev5", "release/", "1!", "24", ".3", "3", undefined, undefined, undefined, undefined, undefined, ".dev5", "5", index: 0, input: "release/v1!24.31.3.dev5", groups: undefined]`
)
